### ISSUE TITLE
Some Python 3.9 functions are used

### ISSUE THREAD

**Issue by aidan5806** [microsoft/sca-fuzzer#1]
There are several instances of python 3.9 functions being used when python 3.7 is the minimum listed version. Supporting python 3.7 would be good for lower bar to entry. An example of the 3.9 function use is the removeprefix function.
https://github.com/microsoft/sca-fuzzer/blob/8bb2efa0383c149f5ce6ac9f21a94a42a5546a5a/src/x86/isa_spec/get_spec.py#L117-L119
https://github.com/microsoft/sca-fuzzer/blob/8bb2efa0383c149f5ce6ac9f21a94a42a5546a5a/src/generator.py#L135
https://github.com/microsoft/sca-fuzzer/blob/8bb2efa0383c149f5ce6ac9f21a94a42a5546a5a/src/generator.py#L223
https://github.com/microsoft/sca-fuzzer/blob/8bb2efa0383c149f5ce6ac9f21a94a42a5546a5a/src/generator.py#L679
At present, each of these could be replaced with a call to an older set of functions, for example:
```
if line.startswith(name):
                operands_raw = line[len(name):].split(",")
            else:
                operands_raw = line.split(",")
```

**Comment by OleksiiOleksenko** [comment]
Thanks for reporting!

That's a mistake in readme, the requirement should be 3.9, I'll fix it.

Even though I agree that 3.7 would lower the entry bar, we opted for 3.9 for future convenience.
