### ISSUE TITLE
Arm Generator creates too many unconditional branches

### ISSUE THREAD

**Issue by aidan5806** [microsoft/sca-fuzzer#37]
Currently the Arm testcase generator seems to produce a high number of unconditional branches. This causes very little variance in the flow of generated binaries. There should be a control or change to maximize/increase the number of conditional branches.

**Comment by cwshugg** [comment]
I took at crack at this and implemented two new config fields that give better control over the program generator's branch placement. I've put my changes onto a separate branch and opened a PR (#38 ).

**Comment by OleksiiOleksenko** [comment]
Fixed now. Just set `min_successors_per_bb` to 2, and most of the test cases will have cond branches.
