### ISSUE TITLE
Make a mirror for the x86 ISA spec

### ISSUE THREAD

**Issue by neelkrish** [microsoft/sca-fuzzer#56]
Can you verify if you are able to fetch: "https://uops.info/instructions_Jan2022.xml". When I run get_spec.py. I am unable to locate this file.

**Comment by OleksiiOleksenko** [comment]
They probably experienced some server issues, it seem to be back now. However, it is a valid concern, we should consider making a mirror of this file somewhere in our infrastructure. Thanks for pointing it out.
