### ISSUE TITLE
Error minimizing test cases: Fences

### ISSUE THREAD

**Issue by Palid0** [microsoft/sca-fuzzer#58]
I encountered what I believe to be unexpected behaviour when running the minimizing function with --add-fences enabled:

(1) I got a random generated x86 program from Revizor using a relatively basic configuration
(2) I tried executing the minimize function on the program (minasms/3f.asm) via the following line:
     ./cli.py minimize -s x86/isa_spec/base.json -c example-config.yaml -i minasms/3.asm -o minasms/3f.asm -n 100 --add-fences
      - This failed, giving the following error message: "generator.AsmParserException: Could not parse line 10 
                                                                                      Reason: Terminator not at the end of BB"
(3) I then minimized this program (into minasms/min3.asm, without adding fences) and tried adding fences to that minimized version 
    with the following line:
       ./cli.py minimize -s x86/isa_spec/base.json -c example-config.yaml -i minasms/min3.asm -o minasms/min3f.asm -n 100 --add-fences
     - This failed too, giving the same error message as the one in (2).
 
There errors were encountered on the 24th of February, with hyperthreading disabled and the latest version of Revizor to that date. The files were later re-fuzzed again in case of false positives, but both files when fuzzed still presented a violation.
I've left a .zip with the two .asm files and the .yaml file which triggered the error. The original test case file was generated with the same configuration as the one used to try to add fences.

[cant-fence.zip](https://github.com/microsoft/sca-fuzzer/files/10944864/cant-fence.zip)

**Comment by OleksiiOleksenko** [comment]
Thanks for reporting the bug!

Unfortunately, I cannot reproduce the bug from the example you sent. Is it possible that you're using an old version of Revizor? Which branch do you have checked out?

**Comment by OleksiiOleksenko** [comment]
Nevermind, I think I know what's happening there. The minimizer tries to insert a fence in-between two terminator instructions in a BB, which an assumption in the assembly parser that all terminators are strictly consecutive.

I'll try to fix it this week.

**Comment by OleksiiOleksenko** [comment]
Should be fixed now. Let me know if the issue still persists for you.
