### ISSUE TITLE
ERROR: Unknown configuration variable enable_faulty_page.  [in big-fuzz.yaml]

### ISSUE THREAD

**Issue by LuChuanV** [microsoft/sca-fuzzer#91]
ERROR: Unknown configuration variable enable_faulty_page.
It's likely a typo in the configuration file.

**Comment by griffinandrew** [comment]
Then when this is commented out it throws an assembler error " 'generated.asm -o generated.o' returned nonzero exit status 1" , "Error: operand type mismatch for 'bt' ".

**Comment by OleksiiOleksenko** [comment]
@LuChuanV Thanks for reporting the issue! This was indeed an outdated field; fixed now (see #493d347).

@griffinandrew I could not reproduce this issue. Could you post `generated.asm` that triggered this error? Also, which branch are you using?

**Comment by griffinandrew** [comment]
@OleksiiOleksenko Thanks for the quick reply, I believe the issue stems from the unavailability of vmlinux on ubuntu 22.04. When I make the kernel module it skips BTF generation which is exactly what the assembler errors on. It is very strange though, the other 2 basic configs listed in the readme run and terminate normally. I am on the main branch. 


![42CACB76-AC3A-4A0A-B45E-52B73CECB43B_1_105_c](https://github.com/microsoft/sca-fuzzer/assets/76177337/3a210253-5749-41f8-93fe-cbf47186a49e)

![IMG_7559](https://github.com/microsoft/sca-fuzzer/assets/76177337/7a21ebc5-1bdc-4ab4-8af9-f6a13a2ec0ae)

![IMG_7561](https://github.com/microsoft/sca-fuzzer/assets/76177337/fda675b0-4457-466c-a542-46172d3e1aa3)

**Comment by OleksiiOleksenko** [comment]
The error is thrown by the assembler when `generator.py` executes `as generated.asm -o generated.o`. This happens before the kernel module is ever called, so I doubt that the error has anything to do with vmlinux.

It looks like something is wrong with the assembler. Could you post the version you're using (run `as -v`)?

Also, could you try assembling the following:

```
.intel_syntax noprefix
BTS EAX, -39
```

by running

```
as assembly_file.asm
```

**Comment by griffinandrew** [comment]
![IMG_7563](https://github.com/microsoft/sca-fuzzer/assets/76177337/0d98e8d5-1e8e-48e4-9843-70c7d7761955)

**Comment by OleksiiOleksenko** [comment]
The issue should be fixed now. Make sure to re-run the `download_spec` command to get an update specification of BT instructions.

@griffinandrew Could you confirm the fix on your setup?
