### ISSUE TITLE
build error - At least one file selection option must be defined in the tool.hatch.build.targets.wheel table

### ISSUE THREAD

**Issue by ItamarGefen** [microsoft/sca-fuzzer#92]
when running `make install` , `python3 -m build` fails with the following error message:
 
>     Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection
> 
>     At least one file selection option must be defined in the tool.hatch.build.targets.wheel table, see: https://hatch.pypa.io/latest/config/build/
> 
>     As an example, if you intend to ship a directory named foo that resides within a src directory located at the root of your project, you can define the following:
> 
>     [tool.hatch.build.targets.wheel]
>     packages = ["src/foo"]

can be fixed by adding this to the `pyproject.toml` file:
```
    ...
    [tool.hatch.build.targets.wheel] 
    packages = ["revizor"]  
```

**Comment by OleksiiOleksenko** [comment]
Thanks for reporting! Fixed as you suggested.
